export { connectToTarget } from './lib/connection'

export { CONNECTION } from './lib/consts/connection'
export { ELEMENT } from './lib/consts/element'
export { ELEMENTS } from './lib/consts/elements'
export { FORM } from './lib/consts/form'
export { INPUT } from './lib/consts/input'
export { NETWORK } from './lib/consts/network'
export { STORE } from './lib/consts/store'
export { WINDOW } from './lib/consts/window'
export { BeamClient } from './lib/client'
export type { IBeamClient } from './lib/client'
